import { Trabajador, VALUES_WORKER } from '../../../trabajador/trabajador-data';
import { Basico, basicos } from '../basicos/basico-data';

export interface Deducciones {
  id: number;
  pensionVoluntaria: number;
  retencionFuente: number;
  afc: number;
  cooperativa: number;
  embargoFiscal: number;
  planComplementarios: number;
  educacion: number;
  reintegro: number;
  deuda: number;
}

export const deducciones: Deducciones[] = [
  {
    id: 1,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 2,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 3,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 4,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 5,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 6,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 7,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 8,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 9,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 10,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 11,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 12,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 13,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 14,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 15,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 16,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 17,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 18,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 19,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
  {
    id: 20,
    pensionVoluntaria: 1,
    retencionFuente: 1,
    afc: 1,
    cooperativa: 1,
    embargoFiscal: 1,
    planComplementarios: 1,
    educacion: 1,
    reintegro: 1,
    deuda: 1,
  },
];

export const displayedColumns: string[] = [
  'deduccion',
  'valor'
];

export const EMPTY = {
  id: 0,
  pensionVoluntaria: 0,
  retencionFuente: 0,
  afc: 0,
  cooperativa: 0,
  embargoFiscal: 0,
  planComplementarios: 0,
  educacion: 0,
  reintegro: 0,
  deuda: 0,
};


export const MENU_ITEMS = [
  { state: 'form', name: 'General deducciónes', type: 'link', icon: 'work', emoji: '1F9FE'  },
  { state: 'anticipos', name: 'Anticipo', type: 'link', icon: 'paid', emoji: '1F9FE'  },
  { state: 'fondo-sp', name: 'Fondo SP', type: 'link', icon: 'local_atm', emoji: '1F4B3'  },
  { state: 'libranzas', name: 'Libranzas', type: 'link', icon: 'local_atm', emoji: '1F4B3'  },
  { state: 'otras-deducciones', name: 'Otras Deducciones', type: 'link', icon: 'money', emoji: '1F3AB'  },
  { state: 'pago-terceros', name: 'Pago a Terceros', type: 'link', icon: 'local_atm', emoji: '1F3AB'  },
  { state: 'sanciones', name: 'Sanciones', type: 'link', icon: 'savings', emoji: '1F39F'  },
  { state: 'salud-pension-sindicato', name: 'salud-pension-sindicato', type: 'link', icon: 'savings', emoji: '1F468'  },
];
