build: 
    stage: build 
    image: weltn24/up-docker-node-chrome-headless
    before_script: 
      - export CHROME_BIN=/usr/bin/google-chrome 
      - npm ci 
 
    script: 
      - npm run build 
      - npm run test:ci 
