/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTAnticiposDto } from './dto/models';
import { ResponseTAnticiposDto } from './dto/models';
import { ResponseTListAnticiposDto } from './dto/models';
import { ResponseTstring } from './dto/models';


import { Configuration }                                     from '../configuration';



export interface AnticiposServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Anticipo in the system.
     *
     * @param id Id Anticipo
     */
    deleteUsingDELETE37(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Anticipo in the system.
     *
     * @param id Id Anticipo
     */
    findByIdUsingGET37(id: string, extraHttpRequestParams?: any): Observable<ResponseTAnticiposDto>;

    /**
     * List all Anticipo in the system.
     *
     */
    getListUsingGET1(extraHttpRequestParams?: any): Observable<ResponseTListAnticiposDto>;

    /**
     * save a Anticipo in the system.
     *
     * @param dto dto
     */
    saveUsingPOST37(dto: RequestTAnticiposDto, extraHttpRequestParams?: any): Observable<ResponseTAnticiposDto>;

    /**
     * update Anticipo in the system.
     *
     * @param dto dto
     */
    updateUsingPUT37(dto: RequestTAnticiposDto, extraHttpRequestParams?: any): Observable<ResponseTAnticiposDto>;

}
