/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTAuxilioDto } from '../model/models';
import { ResponseTAuxilioDto } from '../model/models';
import { ResponseTListAuxilioDto } from '../model/models';
import { ResponseTstring } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuxiliosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Auxilio in the system.
     * 
     * @param id Id Auxilio
     */
    deleteUsingDELETE38(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * List all Auxilio in the system.
     * 
     * @param devengadosId DevengadosId
     */
    findAllDevengadoIdUsingGET2(devengadosId: string, extraHttpRequestParams?: any): Observable<ResponseTListAuxilioDto>;

    /**
     * find by id Auxilio in the system.
     * 
     * @param id Id Auxilio
     */
    findByIdUsingGET38(id: string, extraHttpRequestParams?: any): Observable<ResponseTAuxilioDto>;

    /**
     * save a Auxilio in the system.
     * 
     * @param dto dto
     */
    saveUsingPOST38(dto: RequestTAuxilioDto, extraHttpRequestParams?: any): Observable<ResponseTAuxilioDto>;

    /**
     * update Auxilio in the system.
     * 
     * @param dto dto
     */
    updateUsingPUT38(dto: RequestTAuxilioDto, extraHttpRequestParams?: any): Observable<ResponseTAuxilioDto>;

}
