/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTBonoEpctvDto } from './dto/models';
import { ResponseTBonoEpctvDto } from './dto/models';
import { ResponseTListBonoEpctvDto } from './dto/models';
import { ResponseTstring } from './dto/models';


import { Configuration }                                     from '../configuration';



export interface BonosEPCTVServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete BonoEpctv in the system.
     *
     * @param id Id BonoEpctv
     */
    deleteUsingDELETE41(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id BonoEpctv in the system.
     *
     * @param id Id BonoEpctv
     */
    findByIdUsingGET41(id: string, extraHttpRequestParams?: any): Observable<ResponseTBonoEpctvDto>;

    /**
     * List all BonoEpctv in the system.
     *
     */
    listFindAllUsingGET36(extraHttpRequestParams?: any): Observable<ResponseTListBonoEpctvDto>;

    /**
     * save a BonoEpctv in the system.
     *
     * @param dto dto
     */
    saveUsingPOST41(dto: RequestTBonoEpctvDto, extraHttpRequestParams?: any): Observable<ResponseTBonoEpctvDto>;

    /**
     * update BonoEpctv in the system.
     *
     * @param dto dto
     */
    updateUsingPUT41(dto: RequestTBonoEpctvDto, extraHttpRequestParams?: any): Observable<ResponseTBonoEpctvDto>;

}
