/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTCesantiasDto } from './dto/models';
import { ResponseTCesantiasDto } from './dto/models';
import { ResponseTListHashMapstringobject } from './dto/models';
import { ResponseTstring } from './dto/models';


import { Configuration }                                     from '../configuration';



export interface CesantiasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Cesantias in the system.
     *
     * @param id Id Cesantias
     */
    deleteUsingDELETE42(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Cesantias in the system.
     *
     * @param id Id Cesantias
     */
    findByIdUsingGET42(id: string, extraHttpRequestParams?: any): Observable<ResponseTCesantiasDto>;

    /**
     * List all Cesantias in the system.
     *
     * @param devengadosId DevengadosId
     */
    listFindAllUsingGET37(devengadosId: string, extraHttpRequestParams?: any): Observable<ResponseTListHashMapstringobject>;

    /**
     * save a Cesantias in the system.
     *
     * @param dto dto
     */
    saveUsingPOST42(dto: RequestTCesantiasDto, extraHttpRequestParams?: any): Observable<ResponseTCesantiasDto>;

    /**
     * update Cesantias in the system.
     *
     * @param dto dto
     */
    updateUsingPUT42(dto: RequestTCesantiasDto, extraHttpRequestParams?: any): Observable<ResponseTCesantiasDto>;

}
