/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTFechasPagoDto } from './dto/models';
import { ResponseTFechasPagoDto } from './dto/models';
import { ResponseTListFechasPagoDto } from './dto/models';
import { ResponseTstring } from './dto/models';


import { Configuration }                                     from '../configuration';



export interface FechasPagosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Fecha Pago in the system.
     *
     * @param id Id Fecha Pago
     */
    deleteUsingDELETE48(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Fecha Pago in the system.
     *
     * @param id Id Fecha Pago
     */
    findByIdUsingGET48(id: string, extraHttpRequestParams?: any): Observable<ResponseTFechasPagoDto>;

    /**
     * List all Fecha Pago in the system.
     *
     * @param payrollId PayrollId
     */
    listFindAllUsingGET43(payrollId: string, extraHttpRequestParams?: any): Observable<ResponseTListFechasPagoDto>;

    /**
     * save a Fecha Pago in the system.
     *
     * @param dto dto
     */
    saveUsingPOST48(dto: RequestTFechasPagoDto, extraHttpRequestParams?: any): Observable<ResponseTFechasPagoDto>;

    /**
     * update Fecha Pago in the system.
     *
     * @param dto dto
     */
    updateUsingPUT48(dto: RequestTFechasPagoDto, extraHttpRequestParams?: any): Observable<ResponseTFechasPagoDto>;

}
