/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTHuelgaLegalDto } from './dto/models';
import { ResponseTHuelgaLegalDto } from './dto/models';
import { ResponseTListHuelgaLegalDto } from './dto/models';
import { ResponseTstring } from './dto/models';


import { Configuration }                                     from '../configuration';



export interface HuelgasLegalesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Huelga Legal in the system.
     *
     * @param id Id Huelga Legal
     */
    deleteUsingDELETE51(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Huelga Legal in the system.
     *
     * @param id Id Huelga Legal
     */
    findByIdUsingGET51(id: string, extraHttpRequestParams?: any): Observable<ResponseTHuelgaLegalDto>;

    /**
     * List all Huelga Legal in the system.
     *
     * @param devengadoId DevengadoId
     */
    listFindAllUsingGET46(devengadoId: string, extraHttpRequestParams?: any): Observable<ResponseTListHuelgaLegalDto>;

    /**
     * save a Huelga Legal in the system.
     *
     * @param dto dto
     */
    saveUsingPOST51(dto: RequestTHuelgaLegalDto, extraHttpRequestParams?: any): Observable<ResponseTHuelgaLegalDto>;

    /**
     * update Huelga Legal in the system.
     *
     * @param dto dto
     */
    updateUsingPUT51(dto: RequestTHuelgaLegalDto, extraHttpRequestParams?: any): Observable<ResponseTHuelgaLegalDto>;

}
