/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTInformacionGeneralDto } from './dto/models';
import { ResponseTInformacionGeneralDto } from './dto/models';
import { ResponseTListHashMapstringobject } from './dto/models';
import { ResponseTstring } from './dto/models';


import { Configuration }                                     from '../configuration';



export interface InformacionesGeneralesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Informacion General in the system.
     *
     * @param id Id Informacion General
     */
    deleteUsingDELETE53(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Informacion General in the system.
     *
     * @param id Id Informacion General
     */
    findByIdUsingGET53(id: string, extraHttpRequestParams?: any): Observable<ResponseTInformacionGeneralDto>;

    /**
     * List all Informacion General in the system.
     *
     * @param deducionesId deducionesId
     */
    listFindAllUsingGET48(deducionesId: string, extraHttpRequestParams?: any): Observable<ResponseTListHashMapstringobject>;

    /**
     * save a Informacion General in the system.
     *
     * @param dto dto
     */
    saveUsingPOST53(dto: RequestTInformacionGeneralDto, extraHttpRequestParams?: any): Observable<ResponseTInformacionGeneralDto>;

    /**
     * update Informacion General in the system.
     *
     * @param dto dto
     */
    updateUsingPUT53(dto: RequestTInformacionGeneralDto, extraHttpRequestParams?: any): Observable<ResponseTInformacionGeneralDto>;

}
