/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTLicenciasDto } from '../model/models';
import { ResponseTLicenciasDto } from '../model/models';
import { ResponseTListLicenciasDto } from '../model/models';
import { ResponseTstring } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LicenciasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Licencia in the system.
     * 
     * @param id Id Licencia
     */
    deleteUsingDELETE55(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Licencia in the system.
     * 
     * @param id Id Licencia
     */
    findByIdUsingGET55(id: string, extraHttpRequestParams?: any): Observable<ResponseTLicenciasDto>;

    /**
     * List all Licencia in the system by DevengadosId.
     * 
     * @param devengadosId DevengadosId
     */
    listFindAllDevengadosUsingGET22(devengadosId: string, extraHttpRequestParams?: any): Observable<ResponseTListLicenciasDto>;

    /**
     * List all Licencia in the system.
     * 
     */
    listFindAllUsingGET33(extraHttpRequestParams?: any): Observable<ResponseTListLicenciasDto>;

    /**
     * save a Licencia in the system.
     * 
     * @param dto dto
     */
    saveUsingPOST55(dto: RequestTLicenciasDto, extraHttpRequestParams?: any): Observable<ResponseTLicenciasDto>;

    /**
     * update Licencia in the system.
     * 
     * @param dto dto
     */
    updateUsingPUT55(dto: RequestTLicenciasDto, extraHttpRequestParams?: any): Observable<ResponseTLicenciasDto>;

}
