/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTNominaGeneralDto } from './dto/models';
import { ResponseTListHashMapstringobject } from './dto/models';
import { ResponseTNominaGeneralDto } from './dto/models';


import { Configuration }                                     from '../configuration';



export interface NominasGeneralesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Nomina General in the system.
     *
     * @param id Id Nomina General
     */
    deleteUsingDELETE57(id: string, extraHttpRequestParams?: any): Observable<ResponseTListHashMapstringobject>;

    /**
     * find by id Nomina General in the system.
     *
     * @param id Id Nomina General
     */
    findByIdUsingGET57(id: string, extraHttpRequestParams?: any): Observable<ResponseTNominaGeneralDto>;

    /**
     * List all Nomina General in the system.
     *
     * @param businessSubscriptionId businessSubscriptionId
     */
    listFindAllUsingGET52(businessSubscriptionId: string, extraHttpRequestParams?: any): Observable<ResponseTListHashMapstringobject>;

    /**
     * save a Nomina General in the system.
     *
     * @param dto dto
     */
    saveUsingPOST57(dto: RequestTNominaGeneralDto, extraHttpRequestParams?: any): Observable<ResponseTNominaGeneralDto>;

    /**
     * update Nomina General in the system.
     *
     * @param dto dto
     */
    updateUsingPUT57(dto: RequestTNominaGeneralDto, extraHttpRequestParams?: any): Observable<ResponseTNominaGeneralDto>;

}
