/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTNotasDto } from './dto/models';
import { ResponseTListNotasDto } from './dto/models';
import { ResponseTNotasDto } from './dto/models';
import { ResponseTstring } from './dto/models';


import { Configuration }                                     from '../configuration';



export interface NotasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Nota in the system.
     *
     * @param id Id Nota
     */
    deleteUsingDELETE59(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Nota in the system.
     *
     * @param id Id Nota
     */
    findByIdUsingGET59(id: string, extraHttpRequestParams?: any): Observable<ResponseTNotasDto>;

    /**
     * List all Nota in the system.
     *
     */
    listFindAllUsingGET54(extraHttpRequestParams?: any): Observable<ResponseTListNotasDto>;

    /**
     * save a Nota in the system.
     *
     * @param dto dto
     */
    saveUsingPOST59(dto: RequestTNotasDto, extraHttpRequestParams?: any): Observable<ResponseTNotasDto>;

    /**
     * update Nota in the system.
     *
     * @param dto dto
     */
    updateUsingPUT59(dto: RequestTNotasDto, extraHttpRequestParams?: any): Observable<ResponseTNotasDto>;

}
