/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Configuration } from '../configuration';
import {
  RequestTNumeroSecuenciaXmlDto,
  ResponseTListNumeroSecuenciaXmlDto,
  ResponseTNumeroSecuenciaXmlDto,
  ResponseTstring,
} from '../model/models';

export interface NumerosSecuenciaXMLServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * delete NumeroSecuenciaXml in the system.
   *
   * @param id Id NumeroSecuenciaXml
   */
  deleteUsingDELETE60(
    id: string,
    extraHttpRequestParams?: any
  ): Observable<ResponseTstring>;

  /**
   * find by id NumeroSecuenciaXml in the system.
   *
   * @param id Id NumeroSecuenciaXml
   */
  findByIdUsingGET60(
    id: string,
    extraHttpRequestParams?: any
  ): Observable<ResponseTNumeroSecuenciaXmlDto>;

  /**
   * List all NumeroSecuenciaXml in the system.
   *
   */
  listFindAllUsingGET38(
    extraHttpRequestParams?: any
  ): Observable<ResponseTListNumeroSecuenciaXmlDto>;

  /**
   * save a NumeroSecuenciaXml in the system.
   *
   * @param dto dto
   */
  saveUsingPOST60(
    dto: RequestTNumeroSecuenciaXmlDto,
    extraHttpRequestParams?: any
  ): Observable<ResponseTNumeroSecuenciaXmlDto>;

  /**
   * update NumeroSecuenciaXml in the system.
   *
   * @param dto dto
   */
  updateUsingPUT60(
    dto: RequestTNumeroSecuenciaXmlDto,
    extraHttpRequestParams?: any
  ): Observable<ResponseTNumeroSecuenciaXmlDto>;
}
