/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTPagoTercerosDto } from './dto/models';
import { ResponseTListPagoTercerosDto } from './dto/models';
import { ResponseTPagoTercerosDto } from './dto/models';
import { ResponseTstring } from './dto/models';


import { Configuration }                                     from '../configuration';



export interface PagosTercerosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Pago Terceros in the system.
     *
     * @param id Id Pago Terceros
     */
    deleteUsingDELETE64(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Pago Terceros in the system.
     *
     * @param id Id Pago Terceros
     */
    findByIdUsingGET64(id: string, extraHttpRequestParams?: any): Observable<ResponseTPagoTercerosDto>;

    /**
     * List all Pago Terceros in the system.
     *
     * @param devengadosId DevengadosId
     */
    listFindAllUsingGET59(devengadosId: string, extraHttpRequestParams?: any): Observable<ResponseTListPagoTercerosDto>;

    /**
     * save a Pago Terceros in the system.
     *
     * @param dto dto
     */
    saveUsingPOST64(dto: RequestTPagoTercerosDto, extraHttpRequestParams?: any): Observable<ResponseTPagoTercerosDto>;

    /**
     * update Pago Terceros in the system.
     *
     * @param dto dto
     */
    updateUsingPUT64(dto: RequestTPagoTercerosDto, extraHttpRequestParams?: any): Observable<ResponseTPagoTercerosDto>;

}
