/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTTrabajadorDto } from './dto/models';
import { ResponseTListHashMapstringobject } from './dto/models';
import { ResponseTTrabajadorDto } from './dto/models';
import { ResponseTstring } from './dto/models';


import { Configuration }                                     from '../configuration';



export interface TrabajadoresServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Trabajador in the system.
     *
     * @param id Id Trabajador
     */
    deleteUsingDELETE70(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Trabajador in the system.
     *
     * @param id Id Trabajador
     */
    findByIdUsingGET70(id: string, extraHttpRequestParams?: any): Observable<ResponseTTrabajadorDto>;

    /**
     * List all Trabajador in the system.
     *
     */
    listtrabajadorUsingGET1(extraHttpRequestParams?: any): Observable<ResponseTListHashMapstringobject>;

    /**
     * save a Trabajador in the system.
     *
     * @param dto dto
     */
    saveUsingPOST70(dto: RequestTTrabajadorDto, extraHttpRequestParams?: any): Observable<ResponseTTrabajadorDto>;

    /**
     * update Trabajador in the system.
     *
     * @param dto dto
     */
    updateUsingPUT70(dto: RequestTTrabajadorDto, extraHttpRequestParams?: any): Observable<ResponseTTrabajadorDto>;

}
