/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrabajadorDto { 
    activo: boolean;
    altoRiesgoPension: boolean;
    codigoTrabajador: string;
    id?: string;
    lugarTrabajoDepartamentoEstado: string;
    lugarTrabajoDireccion: string;
    lugarTrabajoMunicipioCiudad: string;
    lugarTrabajoPais: string;
    nominaIndividualId?: string;
    numeroDocumento: string;
    otrosNombres?: string;
    primerApellido: string;
    primerNombre: string;
    salarioIntegral: boolean;
    segundoApellido: string;
    subTipoTrabajador: string;
    sueldo?: number;
    tipoContrato: string;
    tipoDocumento: string;
    tipoTrabajador: string;
}

