export interface ProveedorXML {
  id: number;
  nit?: number;
  otrosNombres?: string;
  primerApellido?: string;
  primerNombre?: string;
  razonSocial?: string;
  segundoApellido?: string;
  softwareId?: string;
  softwareSC?: string;
  dv?: string;
}

export const proveedoresXML: ProveedorXML[] = [
  {
    id: 1,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 2,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 3,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 4,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 5,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 6,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 7,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 8,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 9,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 10,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 11,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 12,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 13,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 14,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 15,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 16,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 17,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 18,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 19,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
  {
    id: 20,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
  },
];

export const displayedColumns: string[] = [
  'id',
  'nit',
  'otrosNombres',
  'primerApellido',
  'primerNombre',
  'razonSocial',
  'segundoApellido',
  'softwareId',
  'softwareSC',
  'dv',
  'action'
];

export const EMPTY = {
  id: 0,
  nit: 0,
  otrosNombres: '',
  primerApellido: '',
  primerNombre: '',
  razonSocial: '',
  segundoApellido: '',
  softwareId: '',
  softwareSC: '',
  dv: '',
};
