/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';


import { Observable }                                        from 'rxjs';

import { Configuration }                                     from './configuration';



export interface StoredProcedureServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns result of stored procedure in the database.
     *
     * @param request request
     */
    exectuteProcedureUsingPOST(request: Request, extraHttpRequestParams?: any): Observable<Response>;

}
