/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BonificacionDto } from './bonificacionDto';
import { CompensacionDto } from './compensacionDto';
import { HorariosAdicionalesDto } from './horariosAdicionalesDto';
import { PrimasDto } from './primasDto';
import { BasicoDto } from './basicoDto';
import { PagoTercerosDto } from './pagoTercerosDto';
import { CesantiasDto } from './cesantiasDto';
import { LicenciasDto } from './licenciasDto';
import { VacacionesComunesDto } from './vacacionesComunesDto';
import { BonoEpctvDto } from './bonoEpctvDto';
import { ComisionDto } from './comisionDto';
import { VacacionesCompensadasDto } from './vacacionesCompensadasDto';
import { OtroConceptoDto } from './otroConceptoDto';
import { AuxilioDto } from './auxilioDto';
import { TransporteDto } from './transporteDto';
import { HuelgaLegalDto } from './huelgaLegalDto';


export interface DevengadosDto { 
    apoyoSost?: number;
    auxilios?: Array<AuxilioDto>;
    basico?: BasicoDto;
    bonifRetiro?: number;
    bonificacions?: Array<BonificacionDto>;
    bonoEpctvs?: Array<BonoEpctvDto>;
    cesantias?: CesantiasDto;
    comisions?: Array<ComisionDto>;
    compensacions?: Array<CompensacionDto>;
    dotacion?: number;
    horariosAdicionaleses?: Array<HorariosAdicionalesDto>;
    huelgaLegals?: Array<HuelgaLegalDto>;
    id?: string;
    indemnizacion?: number;
    licenciases?: Array<LicenciasDto>;
    nominaIndividualId?: string;
    otroConceptos?: Array<OtroConceptoDto>;
    pagoTerceroses?: Array<PagoTercerosDto>;
    primas?: PrimasDto;
    reintegro?: number;
    teletrabajo?: number;
    transporte?: Array<TransporteDto>;
    vacacionesCompensadas?: Array<VacacionesCompensadasDto>;
    vacacionesComuns?: Array<VacacionesComunesDto>;
}

