/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTOtroConceptoDto } from '../model/models';
import { ResponseTListOtroConceptoDto } from '../model/models';
import { ResponseTOtroConceptoDto } from '../model/models';
import { ResponseTstring } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OtrosConceptosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Otro Concepto in the system.
     * 
     * @param id Id Otro Concepto
     */
    deleteUsingDELETE62(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Otro Concepto in the system.
     * 
     * @param id Id Otro Concepto
     */
    findByIdUsingGET62(id: string, extraHttpRequestParams?: any): Observable<ResponseTOtroConceptoDto>;

    /**
     * List all Otro Concepto in the system.
     * 
     * @param devengadosId DevengadosId
     */
    listFindAllDevengadosUsingGET23(devengadosId: string, extraHttpRequestParams?: any): Observable<ResponseTListOtroConceptoDto>;

    /**
     * save a Otro Concepto in the system.
     * 
     * @param dto dto
     */
    saveUsingPOST62(dto: RequestTOtroConceptoDto, extraHttpRequestParams?: any): Observable<ResponseTOtroConceptoDto>;

    /**
     * update Otro Concepto in the system.
     * 
     * @param dto dto
     */
    updateUsingPUT62(dto: RequestTOtroConceptoDto, extraHttpRequestParams?: any): Observable<ResponseTOtroConceptoDto>;

}
