/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTPagoDto } from '../model/models';
import { ResponseTListHashMapstringobject } from '../model/models';
import { ResponseTPagoDto } from '../model/models';
import { ResponseTstring } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PagosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Pago in the system.
     * 
     * @param id Id Pago
     */
    deleteUsingDELETE63(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Pago in the system.
     * 
     * @param id Id Pago
     */
    findByIdUsingGET63(id: string, extraHttpRequestParams?: any): Observable<ResponseTPagoDto>;

    /**
     * List all Pago in the system.
     * 
     * @param payrollId PayrollId
     */
    listFindAllUsingGET40(payrollId: string, extraHttpRequestParams?: any): Observable<ResponseTListHashMapstringobject>;

    /**
     * save a Pago in the system.
     * 
     * @param dto dto
     */
    saveUsingPOST63(dto: RequestTPagoDto, extraHttpRequestParams?: any): Observable<ResponseTPagoDto>;

    /**
     * update Pago in the system.
     * 
     * @param dto dto
     */
    updateUsingPUT63(dto: RequestTPagoDto, extraHttpRequestParams?: any): Observable<ResponseTPagoDto>;

}
