/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTVacacionesCompensadasDto } from '../model/models';
import { ResponseTListVacacionesCompensadasDto } from '../model/models';
import { ResponseTVacacionesCompensadasDto } from '../model/models';
import { ResponseTstring } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface VacacionesCompensadasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Vacaciones Compensada in the system.
     * 
     * @param id Id Vacaciones Compensada
     */
    deleteUsingDELETE72(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Vacaciones Compensada in the system.
     * 
     * @param id Id Vacaciones Compensada
     */
    findByIdUsingGET72(id: string, extraHttpRequestParams?: any): Observable<ResponseTVacacionesCompensadasDto>;

    /**
     * List all Vacaciones Compensada in the system by DevengadosId.
     * 
     * @param devengadosId DevengadosId
     */
    listFindAllDevengadosUsingGET26(devengadosId: string, extraHttpRequestParams?: any): Observable<ResponseTListVacacionesCompensadasDto>;

    /**
     * List all Vacaciones Compensada in the system.
     * 
     */
    listFindAllUsingGET46(extraHttpRequestParams?: any): Observable<ResponseTListVacacionesCompensadasDto>;

    /**
     * save a Vacaciones Compensada in the system.
     * 
     * @param dto dto
     */
    saveUsingPOST72(dto: RequestTVacacionesCompensadasDto, extraHttpRequestParams?: any): Observable<ResponseTVacacionesCompensadasDto>;

    /**
     * update Vacaciones Compensada in the system.
     * 
     * @param dto dto
     */
    updateUsingPUT72(dto: RequestTVacacionesCompensadasDto, extraHttpRequestParams?: any): Observable<ResponseTVacacionesCompensadasDto>;

}
