/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model that represents a Contact of the customer.
 */
export interface Contact { 
    /**
     * The database generated contact ID.
     */
    id?: string;
    /**
     * The name of the contact.
     */
    name?: string;
    /**
     * The telephone number of the contact.
     */
    phone?: string;
    /**
     * The office extension number.
     */
    extension?: string;
    /**
     * The email address of the contact.
     */
    email?: string;
}

