/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model that represents a Credit Note sent.
 */
export interface CreditNoteSent { 
    errors?: Array<object>;
    /**
     * The document number of the credit note.
     */
    docNumber?: string;
    /**
     * The issue date of the credit note.
     */
    issueDate?: string;
    /**
     * The received date of the credit note request.
     */
    receivedDate?: string;
    /**
     * The payable amount of the credit note.
     */
    payableAmount?: number;
}

