/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model that represents an Employee.
 */
export interface Employee { 
    errors?: Array<object>;
    /**
     * The database generated employee ID.
     */
    id?: string;
    /**
     * The email address of the employee.
     */
    email?: string;
    /**
     * The office extension number.
     */
    extension?: string;
    /**
     * Indicates whether the employee is responsible for accounting. True if the employee is responsible; otherwise False.
     */
    accounting?: boolean;
    /**
     * The name of the employee.
     */
    name?: string;
    /**
     * The telephone number of the employee.
     */
    phone?: string;
    /**
     * The position of the employee.
     */
    position?: string;
}

