/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model that represents a Supplier of the invoice for SEND.
 */
export interface NewCreditNoteSupplier { 
    /**
     * The identification type code of the supplier.
     */
    idTypeCode: string;
    /**
     * The identification number of the supplier.
     */
    identificationNumber: string;
    /**
     * The name of the seller contact.
     */
    nameSellerContact: string;
    /**
     * The email of the seller contact.
     */
    emailSellerContact: string;
    /**
     * The phone of the seller contact.
     */
    phoneSellerContact: string;
}

