/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model that represents a Discount Line Detail of the credit note for SEND.
 */
export interface NewCreditNoteLineDiscountDetail { 
    /**
     * The total amount of the discount. Required if DIAN credit note concept code is 1, 3 or 4.
     */
    amount?: number;
    /**
     * The percent of the discount. Required if DIAN credit note concept code is 1, 3 or 4.
     */
    percent?: number;
}

