/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tax } from './tax';


/**
 * Model that represents an Product.
 */
export interface Product { 
    errors?: Array<object>;
    /**
     * The database generated product ID.
     */
    id?: string;
    /**
     * The code of the product.
     */
    code?: string;
    /**
     * The name of the product.
     */
    name?: string;
    /**
     * The price of the product.
     */
    price?: number;
    /**
     * The type name of the product.
     */
    type?: string;
    /**
     * The type code of the product. P: Product, S: Service.
     */
    typeCode?: string;
    /**
     * The unit measure name of the product.
     */
    unitMeasure?: string;
    /**
     * The unit measure code of the product.
     */
    unitMeasureCode?: string;
    /**
     * The taxes of the product.
     */
    taxes?: Array<Tax>;
    /**
     * Allowance code (only Allowance type product)
     */
    allowanceCode?: string;
    /**
     * The nit of the product (only Mandate type product).
     */
    nit?: string;
}

