/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model that represents a Tax Product.
 */
export interface Tax { 
    /**
     * The database generated tax ID.
     */
    id?: string;
    /**
     * The tax rate for the category, expressed as a percentage.
     */
    percent?: number;
    /**
     * The name of the tax category.
     */
    tax?: string;
    /**
     * The code of the tax category.
     */
    taxCode?: string;
    /**
     * The tax rate for the category, expressed as nominal value
     */
    perUnitAmount?: number;
    /**
     * The concept code of the retention
     */
    retentionCode?: string;
}

