/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model that represents an Address of the customer.
 */
export interface Address { 
    /**
     * The database generated address ID.
     */
    id?: string;
    /**
     * The address line description.
     */
    addressLine?: string;
    /**
     * The additional address description like floor, room, block name, building name, department, etc.
     */
    details?: string;
    /**
     * The name of the country.
     */
    country?: string;
    /**
     * The ISO 3166-1 country code. Colombia country code is: \'CO\'.
     */
    countryCode?: string;
    /**
     * The name of the country subdivision.
     */
    subDivision?: string;
    /**
     * The ISO 3166-2 country subdivision code. If Colombia use DANE country subdivision code. Bogotá D.C DANE code is: \'11\'.
     */
    subDivisionCode?: string;
    /**
     * The name of the country subdivision.
     */
    city?: string;
    /**
     * The city code. If Colombia use DANE city code. Bogotá D.C DANE city code is: \'11001\'.
     */
    cityCode?: string;
    /**
     * The telephone number.
     */
    phoneNumber?: string;
    /**
     * The office extension number.
     */
    extensionNumber?: string;
    /**
     * The neighborhood of the addressLine.
     */
    neighborhood?: string;
    /**
     * The store of the addressLine.
     */
    store?: string;
}

