/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NewCreditNoteLineDiscountDetail } from './newCreditNoteLineDiscountDetail';
import { NewCreditNoteLineTaxDetail } from './newCreditNoteLineTaxDetail';


/**
 * Model that represents a Line of the credit note for SEND.
 */
export interface NewCreditNoteLine { 
    /**
     * Is gift indicator
     */
    gift?: boolean;
    /**
     * The item code of the product. Required if DIAN credit note concept code is 1, 3 or 4.
     */
    itemCode?: string;
    /**
     * The additional description of the product. Required only when product type is \'S\'.
     */
    itemDescription?: string;
    /**
     * The credited quantity of the product. Required if DIAN credit note concept code is 1, 3 or 4.
     */
    creditedQuantity?: number;
    /**
     * The price of the product. Required if DIAN credit note concept code is 1, 3 or 4.
     */
    price?: number;
    /**
     * The discount detail of the credit note line.
     */
    creditNoteLineDiscountDetails?: Array<NewCreditNoteLineDiscountDetail>;
    /**
     * The tax detail of the credit note line.
     */
    creditNoteLineTaxDetails?: Array<NewCreditNoteLineTaxDetail>;
    /**
     * The line extension amount of the credit note line.
     */
    lineExtensionAmount: number;
    /**
     * The line extension amount of the credit note line.
     */
    invoiceLineExtensionAmount?: number;
}

