/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NewCreditNoteCustomer } from './newCreditNoteCustomer';
import { NewCreditNoteNote } from './newCreditNoteNote';
import { NewCreditNoteLine } from './newCreditNoteLine';
import { NewCreditNoteSupplier } from './newCreditNoteSupplier';


/**
 * Model that represents a Credit Note for SEND.
 */
export interface NewCreditNote { 
    errors?: Array<object>;
    /**
     * The document number of the credit note.
     */
    docNumber: string;
    /**
     * The issue date of the credit note.
     */
    issueDate: string;
    /**
     * The invoice document number of the credit note.
     */
    invoice: string;
    /**
     * The lines of the credit note.
     */
    creditNoteLines?: Array<NewCreditNoteLine>;
    /**
     * The payable amount of the credit note.
     */
    payableAmount?: number;
    /**
     * The notes of the credit note.
     */
    creditNoteNotes?: Array<NewCreditNoteNote>;
    /**
     * The notification email of the credit note.
     */
    notificationEmail: string;
    /**
     * The concept code of the credit note.
     */
    conceptCode: string;
    /**
     * The type of operation.
     */
    operationType?: string;
    /**
     * The customer party of the credit note.
     */
    creditNoteCustomers?: Array<NewCreditNoteCustomer>;
    /**
     * The supplier party of the credit note.
     */
    creditNoteSuppliers?: Array<NewCreditNoteSupplier>;
    /**
     * The currency of the credit note.
     */
    currencyCode?: string;
    /**
     * The issue date of the invoice.
     */
    invoiceIssueDate?: string;
}

