/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NewDebitNoteLineTaxDetail } from './newDebitNoteLineTaxDetail';


/**
 * Model that represents a Line of the debit note for SEND.
 */
export interface NewDebitNoteLine { 
    /**
     * The item code of the product.
     */
    itemCode: string;
    /**
     * The additional description of the product. Required only when product type is \'S\'.
     */
    itemDescription?: string;
    /**
     * The debited quantity of the product.
     */
    debitedQuantity: number;
    /**
     * The price of the product.
     */
    price: number;
    /**
     * The tax detail of the debit note line.
     */
    debitNoteLineTaxDetails: Array<NewDebitNoteLineTaxDetail>;
    /**
     * The line extension amount of the debit note line.
     */
    lineExtensionAmount: number;
}

