/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NewDebitNoteLine } from './newDebitNoteLine';
import { NewDebitNoteNote } from './newDebitNoteNote';


/**
 * Model that represents a Debit Note for SEND.
 */
export interface NewDebitNote { 
    errors?: Array<object>;
    /**
     * The document number of the debit note.
     */
    docNumber: string;
    /**
     * The issue date of the debit note.
     */
    issueDate: string;
    /**
     * The invoice document number of the debit note.
     */
    invoice: string;
    /**
     * The lines of the debit note.
     */
    debitNoteLines: Array<NewDebitNoteLine>;
    /**
     * The payable amount of the debit note.
     */
    payableAmount: number;
    /**
     * The notes of the debit note.
     */
    debitNoteNotes?: Array<NewDebitNoteNote>;
    /**
     * The concept code of the debit note.
     */
    conceptCode?: string;
    /**
     * The notification email of the debit note.
     */
    notificationEmail: string;
    /**
     * The type of operation.
     */
    operationType?: string;
}

