/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NewInvoiceLineDiscountDetail } from './newInvoiceLineDiscountDetail';
import { NewInvoiceLineTaxDetail } from './newInvoiceLineTaxDetail';


/**
 * Model that represents a Line of the invoice for SEND.
 */
export interface NewInvoiceLine { 
    /**
     * Is gift indicator
     */
    gift?: boolean;
    /**
     * The item code of the product.
     */
    itemCode: string;
    /**
     * The additional description of the product. Required only when product type is \'S\'.
     */
    itemDescription?: string;
    /**
     * The invoiced quantity of the product.
     */
    invoicedQuantity: number;
    /**
     * The price of the product.
     */
    price: number;
    /**
     * The discount detail of the invoice line.
     */
    invoiceLineDiscountDetails?: Array<NewInvoiceLineDiscountDetail>;
    /**
     * The tax detail of the invoice line.
     */
    invoiceLineTaxDetails: Array<NewInvoiceLineTaxDetail>;
    /**
     * The line extension amount of the invoice line.
     */
    lineExtensionAmount: number;
    /**
     * Is Bien Cubierto indicator
     */
    bienCubierto?: boolean;
}

