/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model that represents a Payment Mean of the invoice for SEND.
 */
export interface NewInvoicePaymentMean { 
    /**
     * The maximun number of days to pay the invoice. Required if PaymentMeansCode is \'60\' for Credit.
     */
    days?: number;
    /**
     * The payment due date of the invoice. Required if PaymentMeansCode is \'60\' for Credit.
     */
    paymentDueDate?: string;
    /**
     * The payment mean code of the invoice.
     */
    paymentMeansCode: string;
    /**
     * The mean code of the invoice.
     */
    meansCode?: string;
}

