/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmpleadorDto { 
    departamentoEstado: number;
    direccion: string;
    dv: number;
    id?: string;
    municipioCiudad: number;
    nit: number;
    otrosNombres?: string;
    pais: string;
    primerApellido: string;
    primerNombre: string;
    razonSocial: string;
    segundoApellido: string;
}

