import { ValuesCatalog } from '../../../srv/in-mem-data-service';

export interface Empleador {
  id: number;
  nit?: number;
  otrosNombres?: string;
  primerApellido?: string;
  primerNombre?: string;
  razonSocial?: string;
  segundoApellido?: string;
  softwareId?: string;
  softwareSC?: string;
  dv?: string;
  departamentoEstado?: number;
  pais?: string;
}

export const empleadores: Empleador[] = [
  {
    id: 1,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 2,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 3,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 4,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 5,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 6,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 7,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 8,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 9,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 10,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 11,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 12,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 13,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 14,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 15,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 16,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 17,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 18,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 19,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
  {
    id: 20,
    nit: 12,
    otrosNombres: 'string',
    primerApellido: 'string',
    primerNombre: 'string',
    razonSocial: 'string',
    segundoApellido: 'string',
    softwareId: 'string',
    softwareSC: 'string',
    dv: 'ES',
    departamentoEstado: 1,
    pais: 'CO',
  },
];

export const displayedColumns: string[] = [
  'nit',
  'otrosNombres',
  'primerApellido',
  'primerNombre',
  'razonSocial',
  'segundoApellido',
  'softwareId',
  'softwareSC',
  'dv',
  'departamentoEstado',
  'pais',
  'action',
];

export const EMPTY = {
  id: 0,
  nit: 0,
  otrosNombres: '',
  primerApellido: '',
  primerNombre: '',
  razonSocial: '',
  segundoApellido: '',
  softwareId: '',
  softwareSC: '',
  dv: '',
  departamentoEstado: 1,
  pais: 'CO',
};

export const catalogsDepartamentos: ValuesCatalog[] = [
  { id: 1, code: 'CUND', name: 'Cundinamarca' },
  { id: 2, code: 'CB', name: 'Carabobo' },
];
export const catalogsPaises: ValuesCatalog[] = [
  { id: 1, code: 'CO', name: 'Colombia' },
  { id: 2, code: 'VE', name: 'Venezuela' },
];
