/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTBonificacionDto } from '../model/models';
import { ResponseTBonificacionDto } from '../model/models';
import { ResponseTListBonificacionDto } from '../model/models';
import { ResponseTstring } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BonificacionesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Bonificacion in the system.
     * 
     * @param id Id Bonificacion
     */
    deleteUsingDELETE40(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Bonificacion in the system.
     * 
     * @param id Id Bonificacion
     */
    findByIdUsingGET40(id: string, extraHttpRequestParams?: any): Observable<ResponseTBonificacionDto>;

    /**
     * List all Bonificacion in the system by DevengadosId.
     * 
     * @param devengadosId DevengadosId
     */
    listFindAllDevengadosUsingGET15(devengadosId: string, extraHttpRequestParams?: any): Observable<ResponseTListBonificacionDto>;

    /**
     * save a Bonificacion in the system.
     * 
     * @param dto dto
     */
    saveUsingPOST40(dto: RequestTBonificacionDto, extraHttpRequestParams?: any): Observable<ResponseTBonificacionDto>;

    /**
     * update Bonificacion in the system.
     * 
     * @param dto dto
     */
    updateUsingPUT40(dto: RequestTBonificacionDto, extraHttpRequestParams?: any): Observable<ResponseTBonificacionDto>;

}
