/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Employee } from '../model/models';
import { ResponseEntityOfobject } from '../model/index';


import { Configuration }                                     from '../configuration';



export interface EmployeesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Delete a Employee in the system.
     *
     * @param id id
     */
    deleteEmployeeUsingDELETE(id: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * Find a List of Employees by a List of ID\&#39;s in the system.
     * Also return a link to retrieve all employees with rel employees
     * @param names names
     */
    employeeListByNamesUsingGET(names: Array<string>, extraHttpRequestParams?: any): Observable<Array<ResponseEntityOfobject>>;

    /**
     * Add a new Employee in the system.
     *
     * @param list list
     */
    newEmployeesUsingPOST(list: Array<Employee>, extraHttpRequestParams?: any): Observable<Array<ResponseEntityOfobject>>;

    /**
     * Update a List of Employees in the system.
     *
     * @param list list
     */
    replaceEmployeesUsingPUT(list: Array<Employee>, extraHttpRequestParams?: any): Observable<Array<ResponseEntityOfobject>>;

}
