/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTEmpleadorDto } from '../model/models';
import { ResponseTEmpleadorDto } from '../model/models';
import { ResponseTstring } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EmpleadoresServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Empleador in the system.
     * 
     * @param id Id Empleador
     */
    deleteUsingDELETE47(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * find by id Empleador in the system.
     * 
     * @param id Id Empleador
     */
    findByIdUsingGET47(id: string, extraHttpRequestParams?: any): Observable<ResponseTEmpleadorDto>;

    /**
     * save a Empleador in the system.
     * 
     * @param dto dto
     */
    saveUsingPOST47(dto: RequestTEmpleadorDto, extraHttpRequestParams?: any): Observable<ResponseTEmpleadorDto>;

    /**
     * update Empleador in the system.
     * 
     * @param dto dto
     */
    updateUsingPUT47(dto: RequestTEmpleadorDto, extraHttpRequestParams?: any): Observable<ResponseTEmpleadorDto>;

}
