/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Greeting } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GreetingsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * greeting
     * 
     * @param name name
     */
    greetingUsingDELETE(name?: string, extraHttpRequestParams?: any): Observable<Greeting>;

    /**
     * greeting
     * 
     * @param name name
     */
    greetingUsingGET(name?: string, extraHttpRequestParams?: any): Observable<Greeting>;

    /**
     * greeting
     * 
     * @param name name
     */
    greetingUsingHEAD(name?: string, extraHttpRequestParams?: any): Observable<Greeting>;

    /**
     * greeting
     * 
     * @param name name
     */
    greetingUsingOPTIONS(name?: string, extraHttpRequestParams?: any): Observable<Greeting>;

    /**
     * greeting
     * 
     * @param name name
     */
    greetingUsingPATCH(name?: string, extraHttpRequestParams?: any): Observable<Greeting>;

    /**
     * greeting
     * 
     * @param name name
     */
    greetingUsingPOST(name?: string, extraHttpRequestParams?: any): Observable<Greeting>;

    /**
     * greeting
     * 
     * @param name name
     */
    greetingUsingPUT(name?: string, extraHttpRequestParams?: any): Observable<Greeting>;

}
