/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RequestTHorariosAdicionalesDto } from '../model/models';
import { ResponseTHorariosAdicionalesDto } from '../model/models';
import { ResponseTListHorariosAdicionalesDto } from '../model/models';
import { ResponseTstring } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HorariosAdicionalesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * delete Horarios adicional in the system.
     * 
     * @param id Id Horarios adiccional
     */
    deleteUsingDELETE50(id: string, extraHttpRequestParams?: any): Observable<ResponseTstring>;

    /**
     * List all Horarios adicional in the system.
     * 
     * @param devengadosId DevengadosId
     */
    findAllDevengadoIdUsingGET3(devengadosId: string, extraHttpRequestParams?: any): Observable<ResponseTListHorariosAdicionalesDto>;

    /**
     * find by id Horarios adicional in the system.
     * 
     * @param id Id Horarios adiccional
     */
    findByIdUsingGET50(id: string, extraHttpRequestParams?: any): Observable<ResponseTHorariosAdicionalesDto>;

    /**
     * save a Horarios adicional in the system.
     * 
     * @param dto dto
     */
    saveUsingPOST50(dto: RequestTHorariosAdicionalesDto, extraHttpRequestParams?: any): Observable<ResponseTHorariosAdicionalesDto>;

    /**
     * update Horarios adicional in the system.
     * 
     * @param dto dto
     */
    updateUsingPUT50(dto: RequestTHorariosAdicionalesDto, extraHttpRequestParams?: any): Observable<ResponseTHorariosAdicionalesDto>;

}
