/**
 * FPI E-Invoice API
 * The FPI E-Invoice API allows your applications to retrieve products, customers and manage electronic document exchange.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@fpicolombia.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { InvoiceSent } from '../model/models';
import { NewInvoice } from '../model/models';
import { ResponseEntityOfobject } from '../model/index';


import { Configuration }                                     from '../configuration';



export interface InvoicesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns list of all Billing Range of the invoice in the system.
     *
     */
    getBillingRangesUsingGET2(extraHttpRequestParams?: any): Observable<Array<ResponseEntityOfobject>>;

    /**
     * Find a Invoice by docNumber in the system.
     *
     * @param docNumbers docNumbers
     */
    invoiceListUsingGET(docNumbers: Array<string>, extraHttpRequestParams?: any): Observable<Array<ResponseEntityOfobject>>;

    /**
     * Send a Invoice to prepare and send the document to DIAN.
     *
     * @param list list
     */
    sendListUsingPOST2(list: Array<NewInvoice>, extraHttpRequestParams?: any): Observable<Array<ResponseEntityOfobject>>;

}
