import { Trabajador, VALUES_WORKER } from '../../../trabajador/trabajador-data';
import { Basico, basicos } from '../basicos/basico-data';

export interface Devengados {
  id: number;
  basicoId: number;
  primasId: number;
  cesantiasId: number;
  dotacion?: number;
  apoyoSost?: number;
  teletrabajo?: number;
  bonifRetiro?: number;
  indemnizacion?: number;
  reintegro?: number;
  basico?: Basico;
  trabajador?: Trabajador;
}

export const devengados: Devengados[] = [
  {
    id: 1,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 2,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 3,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 4,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 5,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 6,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 7,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 8,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 9,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 10,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 11,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 12,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 13,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 14,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 15,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 16,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 17,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 18,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 19,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 20,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
];

export const displayedColumns: string[] = [
  'id',
  'basicoId',
  'primasId',
  'cesantiasId',
  'dotacion',
  'apoyoSost',
  'teletrabajo',
  'bonifRetiro',
  'indemnizacion',
  'reintegro',
  'action',
];

export const EMPTY = {
  id: 0,
  basicoId: 1,
  primasId: 1,
  cesantiasId: 1,
  dotacion: 0,
  apoyoSost: 0,
  teletrabajo: 0,
  bonifRetiro: 0,
  indemnizacion: 0,
  reintegro: 1,
  basico: basicos[0],
  trabajador: VALUES_WORKER[0],
};


export const MENU_ITEMS = [
  { state: '/', name: 'General devengos', type: 'link', icon: 'work', emoji: '1F4B5' },
  { state: 'anticipos', name: 'Anticipo', type: 'link', icon: 'paid', emoji: '1F9FE' },
  { state: 'auxilios', name: 'Auxilios', type: 'link', icon: 'local_atm', emoji: '1F4B8' },
  { state: 'bonificaciones', name: 'Bonificación', type: 'link', icon: 'money', emoji: '1F4B6' },
  { state: 'bonos', name: 'Bonos', type: 'link', icon: 'local_atm', emoji: '1F4B6' },
  { state: 'cesantías', name: 'Cesantías', type: 'link', icon: 'savings', emoji: '1F416' },
  { state: 'comisiones', name: 'Comisiones', type: 'link', icon: 'price_check', emoji: '1F949' },
  { state: 'compensaciones', name: 'Compensaciones', type: 'link', icon: 'shopping_basket', emoji: '1F381' },
  { state: 'horariosAdicionales', name: 'Horario Adicional', type: 'link', icon: 'receipt', emoji: '1F555' },
  { state: 'huelgas-legales', name: 'Huelga Legal', type: 'link', icon: 'receipt', emoji: '1F555' },
  { state: 'incapacidades', name: 'Incapacidades', type: 'link', icon: 'receipt', emoji: '1F39F' },
  { state: 'licencias', name: 'Licencias', type: 'link', icon: 'receipt', emoji: '1F39F' },
  { state: 'otrosConceptos', name: 'Otros Conceptos', type: 'link', icon: 'receipt', emoji: '1F4B5' },
  { state: 'pagosTerceros', name: 'Pagos de Tercero', type: 'link', icon: 'payments', emoji: '1F4B0' },
  { state: 'transportes', name: 'Transporte', type: 'link', icon: 'transfer_within_a_station', emoji: '1F695' },
  { state: 'vacaciones', name: 'Vacaciones', type: 'link', icon: 'flight_takeoff', emoji: '1F305' },
];
