import { Trabajador, VALUES_WORKER } from '../../../trabajador/trabajador-data';
import { Basico, basicos } from '../basicos/basico-data';

export interface Devengados {
  id: number;
  basicoId: number;
  primasId: number;
  cesantiasId: number;
  dotacion?: number;
  apoyoSost?: number;
  teletrabajo?: number;
  bonifRetiro?: number;
  indemnizacion?: number;
  reintegro?: number;
  basico?: Basico;
  trabajador?: Trabajador;
}

export const devengados: Devengados[] = [
  {
    id: 1,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 2,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 3,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 4,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 5,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 6,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 7,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 8,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 9,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 10,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 11,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 12,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 13,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 14,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 15,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 16,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 17,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 18,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 19,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
  {
    id: 20,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
    basico: basicos[0],
    trabajador: VALUES_WORKER[0],
  },
];

export const displayedColumns: string[] = [
  'id',
  'basicoId',
  'primasId',
  'cesantiasId',
  'dotacion',
  'apoyoSost',
  'teletrabajo',
  'bonifRetiro',
  'indemnizacion',
  'reintegro',
  'action',
];

export const EMPTY = {
  id: 0,
  basicoId: 1,
  primasId: 1,
  cesantiasId: 1,
  dotacion: 0,
  apoyoSost: 0,
  teletrabajo: 0,
  bonifRetiro: 0,
  indemnizacion: 0,
  reintegro: 1,
  basico: basicos[0],
  trabajador: VALUES_WORKER[0],
};


export const MENU_ITEMS = [
  { state: '/nómina/devengos/view/form', name: 'General devengos', type: 'link', icon: 'work' },
  { state: '/nómina/devengos/view/anticipos', name: 'Anticipo', type: 'link', icon: 'paid' },
  { state: '/nómina/devengos/view/auxilios', name: 'Auxilios', type: 'link', icon: 'local_atm' },
  { state: '/nómina/devengos/view/bonificaciones', name: 'Bonificación', type: 'link', icon: 'money' },
  { state: '/nómina/devengos/view/bonos', name: 'Bonos', type: 'link', icon: 'local_atm' },
  { state: '/nómina/devengos/view/cesantías', name: 'Cesantías', type: 'link', icon: 'savings' },
  { state: '/nómina/devengos/view/comisiones', name: 'Comisión', type: 'link', icon: 'price_check' },
  { state: '/nómina/devengos/view/compensaciones', name: 'Compensaciones', type: 'link', icon: 'shopping_basket' },
  { state: '/nómina/devengos/view/horariosAdicionales', name: 'Horarios Adicionales', type: 'link', icon: 'receipt' },
  { state: '/nómina/devengos/view/licencias', name: 'Licencias', type: 'link', icon: 'receipt' },
  { state: '/nómina/devengos/view/otrosConceptos', name: 'Otros Conceptos', type: 'link', icon: 'receipt' },
  { state: '/nómina/devengos/view/pagosTerceros', name: 'Pagos de Tercero', type: 'link', icon: 'payments' },
  { state: '/nómina/devengos/view/transportes', name: 'Transporte', type: 'link', icon: 'transfer_within_a_station' },
  { state: '/nómina/devengos/view/vacaciones', name: 'Vacaciones', type: 'link', icon: 'flight_takeoff' },
];
