import { ValuesCatalog } from '../../../srv/in-mem-data-service';

export interface Devengados {
  id: number;
  basicoId: number;
  primasId: number;
  cesantiasId: number;
  dotacion?: number;
  apoyoSost?: number;
  teletrabajo?: number;
  bonifRetiro?: number;
  indemnizacion?: number;
  reintegro?: number;
}

export const devengados: Devengados[] = [
  {
    id: 1,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 2,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 3,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 4,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 5,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 6,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 7,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 8,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 9,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 10,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 11,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 12,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 13,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 14,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 15,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 16,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 17,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 18,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 19,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
  {
    id: 20,
    basicoId: 1,
    primasId: 1,
    cesantiasId: 1,
    dotacion: 12,
    apoyoSost: 34,
    teletrabajo: 34,
    bonifRetiro: 34,
    indemnizacion: 34,
    reintegro: 1,
  },
];

export const displayedColumns: string[] = [
  'id',
  'basicoId',
  'primasId',
  'cesantiasId',
  'dotacion',
  'apoyoSost',
  'teletrabajo',
  'bonifRetiro',
  'indemnizacion',
  'reintegro',
  'action',
];

export const EMPTY = {
  id: 0,
  basicoId: 1,
  primasId: 1,
  cesantiasId: 1,
  dotacion: 0,
  apoyoSost: 0,
  teletrabajo: 0,
  bonifRetiro: 0,
  indemnizacion: 0,
  reintegro: 1,
};

